### ISSUE TITLE
Build on Android only showing Postcard Logo

### ISSUE THREAD

**Issue by Jambajoo** [thaliproject/postcardapp#118]
Hi I can't get the app to work. Not sure if it was just the iframe or the whole build. Just followed instructions from readme. Here's a screenshot. 

![12648137_10208111302874865_1673477298_n](https://cloud.githubusercontent.com/assets/17076028/12835796/441b89fc-cbee-11e5-9204-13b91bf373b2.jpg)

**Comment by deadlyfingers** [comment]
@tongkolizer can you post your logs - just to see the error. Are you building the master branch?

**Comment by Jambajoo** [comment]
@deadlyfingers  yep from the master branch indeed. There's a development btw. It still shows the postcard logo but shows an error that says 

`"cannot find module 'is-property'"`

Here's a screenshot : 

![image](https://cloud.githubusercontent.com/assets/17076028/12854137/ec0ca8e2-cc72-11e5-990d-ea714d891540.png)

**Comment by Jambajoo** [comment]
@deadlyfingers I got it working now :+1: 

Need to know how this one works tho. I mean I want to see it work device to device.

**Comment by deadlyfingers** [comment]
@tongkolizer you got it working so I intend to close this issue. 
Btw if you had to do anything that was not listed on the Readme to get this working please add comment below as it might be beneficial to add to our documentation.

**Comment by deadlyfingers** [comment]
Todo: Raise PR for merging story_001_dadougla branch into master after Cordova 6 updates.

**Comment by deadlyfingers** [comment]
Created PR to merge into master.

**Comment by Astriel** [comment]
Got exactly the same problem, did someone found a solution for that problem ?

**Comment by yaronyg** [comment]
@Astriel EEEK! O.k. I'm going to go now and put a big warning on this app. It's hopelessly out of date and we have zero resources to update it. :( Our main line code (e.g. https://github.com/thaliproject/Thali_CordovaPlugin) is working. But this demo is based on an ancient version of the code. Sorry. :(

@mospired Any hope of a public video of the Ushahidi demo code we did in SF so we can show Thali in a new video for http://thaliproject.org? It would at least let people see the thing working. Also are there any plans to open source the demo code? It would be an awesome replacement for the postcard app.

**Comment by Astriel** [comment]
Thanks a lot @yaronyg for your answer. I was struggling since two days to be able to implement that mobile application, I'm near the end but still stucked. This is a technology I really need, but I thought this app would be good to have a start. Maybe I can start implementing it on my own with the plugin directly ? That would be a better idea I guess. 

If you have a public video of a demo, that would be amazing !

**Comment by yaronyg** [comment]
@Astriel Check out https://github.com/thaliproject/ThaliTestApp. It's not pretty but we use it for replicating bugs we find with our customer. It should show you the basics. I'd love to hear more about what you are up to if you are able to share. You can reach me at yarong@[Insert large software company here whose name rhymes with icrosoft].com. Thanks!

**Comment by Astriel** [comment]
Thanks a lot @yaronyg, I'll take a deep look and I'm sending you an email to explain you my goal :) ! Thanks a lot for the feedback it's very appreciated, I was starting to be despressed to not be able to play with that technology ahah !
