### ISSUE TITLE
We need UX elements to expose connectivity information

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#19]
#63 will add events to the replication manager to state when we have discovered someone and when we are connected to the. So now we need a way to expose that information in the UX so that people can quickly see if they have successfully found/connected to anyone.

**Comment by deadlyfingers** [comment]
A toggle button can be added into Postcard toolbar to show/hide console log.

**Comment by deadlyfingers** [comment]
Also add button to delete doucments db here

**Comment by deadlyfingers** [comment]
I have a developer interface available to help show this, but need to wire up the native console logs to the webview textarea... or will this be done with Thali logger?

**Comment by yaronyg** [comment]
11/3 - There is an interface that is here but it needs to be wired up.

**Comment by deadlyfingers** [comment]
@mattpodwysocki what I do need to get native logs in the webview textarea console. Is it just a case of making a route for thalilogger function - if so is it a stream?

**Comment by deadlyfingers** [comment]
Matt is going to fire an event using socket.io which I can listen to and update the webview textarea.

**Comment by mattpodwysocki** [comment]
@deadlyfingers here is the way to emit both the network changed data as well as the peers:

``` js
manager._emitter.on('peerAvailabilityChanged', function (peers) {
  io.emit('peerAvailabilityChanged', peers); // this is a list of peers, pick peerName if you want or peerIdentifier
});

manager._emitter.on('networkChanged', function (isAvailable) {
  io.emit('networkChanged', isAvailable);
});
```

**Comment by deadlyfingers** [comment]
@DrJukka noticed an issue while testing networkChanged on Android 
postcard app becomes unresponsive.

```
PostcardApp is not responding.
Would you like to close it?
```
- To recreate turn on Aeroplane mode.

**Comment by DrJukka** [comment]
Can we reproduce this and have logs ?
