### ISSUE TITLE
Please fix our node.js logging

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#22]
Please make sure that all console.logs are removed and replaced with our Winston logging. Talk with @mpodwysocki for the details.

**Comment by deadlyfingers** [comment]
@mpodwysocki What do I need to hook Winston logging up? Right now I have a script with global scope log(message) to write messages to `<textarea>` lines. Also can I use this for Story_0 or this a 0.0.1 feature only? Was thinking it might also be good to set a limit on number of lines eg. 50-100

**Comment by mattpodwysocki** [comment]
@deadlyfingers anywhere we have console.log, we need to call the ThaliLogger.  On the front end, you can send messages via an express endpoint to get logged by the ThaliLogger

**Comment by deadlyfingers** [comment]
Linked to issue #19
