### ISSUE TITLE
Include Python is the dependencies list

### ISSUE THREAD

**Issue by traceyt** [thaliproject/postcardapp#23]
Include "npm install -g python" in the dependencies section.

**Comment by yaronyg** [comment]
@traceyt , thanks for filing this. You have to follow all the directions at https://github.com/TooTallNate/node-gyp#installation. @mpodwysocki is filing a PR now to update the readme for both this project and Thali_CordovaPlugin to point this out for Windows folks. We will keep this issue open until you are successfully building.

**Comment by mpodwysocki** [comment]
@traceyt @yaronyg this is being fixed by https://github.com/thaliproject/postcardapp/pull/24

**Comment by yaronyg** [comment]
I just committed it. @traceyt please let us know if the new instructions work.

**Comment by deadlyfingers** [comment]
No longer appears to cause a problem - we should close this issue.
Unless it is needed for Windows installation?
