### ISSUE TITLE
The "find" command in bash does not support "-delete"

### ISSUE THREAD

**Issue by traceyt** [thaliproject/postcardapp#25]
I was able to get the old fashioned way to work  "find . -name '.gz' -exec rm -rf {} \;" but I did run into "file or path name too long" errors.

**Comment by yaronyg** [comment]
Sigh... the joy of Windows. This is an endemic problem to node on Windows. Node likes to nest things very deep and often ends up with nested paths that are longer than windows can handle.

But the good news is that JXcore has added an 'autoremove' feature. Can you please run `jx -jxv`? If the result is less than v 0.3.0.5 can you please go to http://jxcore.com/downloads/ and download the latest Windows installer? Then when following the instructions [here](https://github.com/thaliproject/postcardapp/tree/story_0#building-the-postcard-app-on-android) please change `jx npm install --production` to instead be `jx npm install --production --autoremove "*.gz"`

That will get rid of 'find' all together. I'm going to go update the build instructions now. I'll close this bug once they are update.

**Comment by yaronyg** [comment]
This should now be fully fixed in the readme.
