### ISSUE TITLE
Connect identity exchange UX to REST back end

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#51]
We need the existing identity exchange UX which is talking to a mock of the REST backend for identity exchange to talk to the real thing.

**Comment by yaronyg** [comment]
10/21 - Was spent on solidifying story 0 and now just moving to story 0.0.1.

**Comment by yaronyg** [comment]
10/30 - Will start working on this (finally!) today!!!! First step is to merge thali_cordovaplugin 0.0.1 into the postcard app.

**Comment by yaronyg** [comment]
11/2 - Just starting to work on some issues with the mock UX and working with the REST API.

**Comment by deadlyfingers** [comment]
Reworking user login from story_0 to story_001 spec.

It it okay to call `webview/DeviceIdentity` at app launch without stopping TRM - this procedure is just needed while `webview/IdentityExchange` is running?

**Comment by yaronyg** [comment]
Yes, it's fine. You should be able to call DeviceIdentity at any time. If not then we have a bug.

**Comment by deadlyfingers** [comment]
Getting a 400 error when trying to pair atm 

```
ExecuteExchange peerDeviceId:F8:CF:C5:7A:32:6A
http://localhost:5000/webview/IdentityExchange/ExecuteExchange Failed to load resource: the server responded with a status of 400 (Bad Request)
page-pair.html:112 Error, could not Execute Exchange. error
```

Update: working now - was using a different case!

**Comment by deadlyfingers** [comment]
Potentially found another issue to raise? As we will be using the DK-hash as Id for Postcards the value needs to support REST. Sometimes the hash contains '/' or other invalid characters which results in a 404 error as the url thinks its a dir and can't resolve it as a PouchDB filename Id.

Also means I can't save the contact if their DK-hash contains a slash '/' char.

**Comment by yaronyg** [comment]
11/9 - working but we have to get it working with #55

**Comment by yaronyg** [comment]
11/9 - Needs some finishing, hoping for PR on 11/10.

**Comment by deadlyfingers** [comment]
@mattpodwysocki peerFriendlyName seems to duplicate on requests?

```
I/jxcore-log( 2048): INFO identityExchange We will advertise the following device name as we start: /X8v+Cl+Q8+UhCPbyXi07Q==;sony
I/jxcore-log( 2048):
I/jxcore-log( 2048): INFO identityExchange We will advertise the following device name as we start: /X8v+Cl+Q8+UhCPbyXi07Q==;sony;sony
```

**Comment by yaronyg** [comment]
@deadlyfingers please follow up with @mattpodwysocki , this looks like a pretty straight forward bug.

**Comment by deadlyfingers** [comment]
Couple of things to review:
- If you have an illegal url char in DeviceIdentity - no REST calls will work.
- Sometimes I have to reset my Android phones to get PUT /webview/IdentityExchange working. (think maybe one of my phones is a bad peer!)
