### ISSUE TITLE
JX install is broken for postcard app

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#60]
Right now JX doesn't reliably download and kills our build so we need to fix it. The claim is that the newer script runs more reliably so we want to try and test that.

**Comment by deadlyfingers** [comment]
Tried with "thali": "^2.0.1" which installs the JXCore plugin automatically... BUT Postcard story_0 didn't sync on Android/iOS. From looking at the logs I need to remove the random string param from: 
https://github.com/thaliproject/postcardapp/blob/master/www/jxcore/app.js#L48
- Upon removing this param it works - is suitable for Story_0? So far it works well on iOS and Android.
