### ISSUE TITLE
Please checkin SVG version of postcard app icon to github

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#64]

**Comment by deadlyfingers** [comment]
It's already in the repro on story_001
www/jxcore/img/logo.png and
www/jxcore/img/logo@2x.png for retina screens

I have included the SVG version in the archive but it doesn't have the stamp effect:
 https://onedrive.live.com/redir?resid=C04BD5A39247EDB0!75130&authkey=!AKt6TjzDPfmVhPg&ithint=file%2czip
