### ISSUE TITLE
Edit my postcards

### ISSUE THREAD

**Issue by deadlyfingers** [thaliproject/postcardapp#70]
Limit edit to only my postcards.

We could also do with adding some UX around this...
For example: view/filter "my postcards" so you can edit/delete your cards from there. Otherwise the main view would be read only.

**Comment by deadlyfingers** [comment]
This would also mean that you can only delete your own postcards.

**Comment by yaronyg** [comment]
Working just need to test

**Comment by deadlyfingers** [comment]
Having some issues with bindings. Unfortunately filtering iron-list isn't supported as yet (https://github.com/PolymerElements/iron-list/issues/123), so having to use another iron-list to display edit my postcards. 
- Ended up stripping the bindings from the original list data and then binding the cloned (filtered) rows to another iron-list using a calulated property
