### ISSUE TITLE
Make sure the postcard app can run in a normal desktop browser

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#84]
We want to do a demo next year of the postcard app where we run JXcore on the desktop (e.g. Linux, OS/X and Win32) with express running and then point a browser (Chrome? Firefox? Whatever) at it and use the Postcard app at least enough to create/delete/update local postcards. I'm hoping we'll integrate in WiFi so we can also show sync but that's a nice to have.

My question for @deadlyfingers is - will the postcard app behave itself in a normal browser? For example, the photo feature, is that run via the HTML 5 photo api or something else? What will break?

**Comment by deadlyfingers** [comment]
@yaronyg Yes, everything should be made to work locally as it's quicker to dev on that environment. This includes simulating native functions like the camera button which triggers a user file upload on desktop. Obviously things like Identity Exchange are faked on desktop for testing the UX and that would need to be looked at. The new gulp build system should also help to target different environments. At the minute its just being used to build for mobile (Android and iOS) but this could be extended for desktop.

**Comment by yaronyg** [comment]
The trick I'm looking for is that we can make it run "live". That is, we drop any mocks or faked things and just use the normal URLs, ports, etc. It sounds like it should more or less work though.
