### ISSUE TITLE
Sync only changes means cards are not always ordered by time

### ISSUE THREAD

**Issue by deadlyfingers** [thaliproject/postcardapp#86]
If a phone starts syncing then 'new' cards are pushed to the top of the list.
This is normally a good thing but strictly speaking these 'new' cards will not be sorted by time.
This is a UX concern and it maybe me being fussy?

**Comment by yaronyg** [comment]
I don't think it's unreasonable to have a time stamp on each card and order by the time stamp.

**Comment by deadlyfingers** [comment]
Also as we are using human readable times using moment js the dates would need to be updated in the list at least every minute. Although when scrolling the list the values will refresh as the model calculates a new value.
