### ISSUE TITLE
Serve web app as compressed .gz files

### ISSUE THREAD

**Issue by deadlyfingers** [thaliproject/postcardapp#96]
We could modify Express to serve the web app using gzip compression (if supported on target platforms)

**Comment by yaronyg** [comment]
We _MUST_ turn this on. We are running over super constrained transports and it's a negotiation item anyway so if the client doesn't support it then nothing bad happens, we'll just default to not using GZIP.

**Comment by mpodwysocki** [comment]
@deadlyfingers @yaronyg there is already compression middleware out there https://github.com/expressjs/compression which is supported by the express organization

**Comment by deadlyfingers** [comment]
Also bodyparser middleware inflates deflated (compressed) bodies by default - 
https://github.com/expressjs/body-parser

**Comment by deadlyfingers** [comment]
Added compression node module to packages and app.js 
"The middleware will attempt to compress response bodies for all request that traverse through the middleware"
- Will need to inspect mobile sessions to verify if responses are compressed.

**Comment by deadlyfingers** [comment]
Will try verifying compression using Fiddler / Charles:
https://www.telerik.com/download/fiddler
https://www.charlesproxy.com/

**Comment by deadlyfingers** [comment]
Tested on localhost and Compression was 27.7% so that's a start.
